version: '3.3'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
      - ./docker/configs/laravel.env:/var/www/html/.env
    ports:
      - "80:80"
    env_file:
      - ./docker/configs/laravel.env
    networks:
      - laravel
  mysql-db:
    image: mysql:5.7.36
    restart: unless-stopped
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./src/tests/dump/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    tty: true
    ports:
      - "3306:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    volumes:
      - ./docker/configs/pma.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge